# -*- coding: utf-8 -*-
"""Tutorial_01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11rXnYd4RHqKkRpbUs5L4wAHBuEHjVgvs
"""

import tensorflow as tf

# INITIALIZATION OF TENSORS
x = tf.constant(4, shape=(1,1), dtype = tf.float64)
x = tf.constant([[1,2,3],[4,5,6]])
x = tf.range(start = 1, limit = 10, delta = 2)
x = tf.cast(x, dtype = tf.float64)

print(x)

# MATHEMATICAL OPERATIONS
x = tf.constant([1,2,3])
y = tf.constant([9,8,7])

z = tf.add(x, y)
z = x + y

z = tf.tensordot(x, y, axes = 1)

print(z)

# INDEXING
x = tf.constant([0,1,1,2,3,1,2,3])

print(x)